### ISSUE TITLE
OTX fails to open on macOS

### ISSUE THREAD

**Issue by artisteacher** [manongjohn/OTX#1]
### Issue Summary

OTX will not open on macOS due to a missing library. So far, I've only been able to test in High Sierra on an old MacBook Pro & an old iMac.
### Screenshot or Video Reference

![Screen Shot 2019-05-28 at 10 20 46 AM](https://user-images.githubusercontent.com/21159116/58485669-76068f00-8132-11e9-8da8-3788d1700e2f.png)
Problem report:
[otx_library.txt](https://github.com/manongjohn/OTX/files/3228106/otx_library.txt)

### Steps to Reproduce

1. In Finder, right-click on package to open
2. Right-click on OTX app to open
3. Ignore unknown developer warning & allow OTX to open
4. "OTX cannot be opened" warning appears

### System Information
* **OpenToonz Version**: OTX Nightly Builds 2019-05-28 & 2019-05-26
* **Operating System**: 10.13.6
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by manongjohn** [comment]
Strange.   Travis builds on Sierra and I am able to open in my Mojave VM without issue though I already have OT installed and running on there.

The systems you tried it on, is OT already installed on those machines?

I'll look more into it.

**Comment by artisteacher** [comment]
Yes, both have OT installed already. Thanks!

**Comment by manongjohn** [comment]
I found out what was wrong. I have to copy the QT framework into the app since it is currently set to look for it on the system in a specific spot which might not be there on all systems.

I have updated my script to build the release package and I am currently testing it out. As soon as I've verified it works, I'll issue a new build.

**Comment by artisteacher** [comment]
Great! I'm looking forward to trying it out.

**Comment by manongjohn** [comment]
Ok. I think I fixed it. A new nightly has been created.  Please check it out and let me know.  I'll keep this open until I hear from you.

**Comment by artisteacher** [comment]
Unfortunately OTX still fails to open. Now there's no problem reported & no crash/problem report. I did see this in console:
![Screen Shot 2019-05-30 at 9 09 01 AM](https://user-images.githubusercontent.com/21159116/58635080-ee985780-82ba-11e9-9b2f-0440e10a250c.png)
and this:
![Screen Shot 2019-05-30 at 9 09 43 AM](https://user-images.githubusercontent.com/21159116/58635081-f0621b00-82ba-11e9-916e-0943558334c2.png)

**Comment by manongjohn** [comment]
I know the 1st time I tried to open it, it went through the verification process and opened a popup asking me about opening it. When I clicked on "Open" button, it just closed.  However, when I tried to open it again, it didn't verify and it opened successfully.   So repeated attempts to open it still doesn't start OTX and no crash reports?

I know while testing it, sometimes the crash message didn't come up and I had to try a second time before I got a crash message.

**Comment by artisteacher** [comment]
I got it to open! So it won't let you launch directly from the dmg - which I'm pretty sure I've done before. The dmg also needs to be unmounted before trying to open the app. Afterwards, the first try failed but the second attempt opened successfully.

**Comment by artisteacher** [comment]
Also thanks so much! It's really fun trying out the new features/fixes.

**Comment by manongjohn** [comment]
Great! Glad you were able to open it. 

Yeah, can't run it from dmg. I wouldn't do that considering it will try to write to the portablestuff hidden in the application itself which is still inside the dmg and I don't think it can write to it like that.

I haven't had any issues with the dmg still mounted and running OTX. What error/issue are you getting?

I'm not entirely sure why it fails to run the 1st time without any errors but then runs fine after that.  The logs don't give me much info to go on. unfortunately.

Let me know if you find anything else. I'll consider this issue closed.

**Comment by artisteacher** [comment]
There's no error report, so it's hard to say. The app icon bounces in the dock and after pressing "open" on the unknown developer warning, the icon immediately disappears and opening fails.
